#!/usr/bin/env python
""" A VOSpace admintool
"""

import sys
import logging
from lineparser import *
from admintask import *

class Admin():
  """Root class for admin"""

if __name__ == "__main__":

    admintool = None
    
    # Supported tasks
    tasks = {'init': Init,
             'adduser': AddUser,
             'validate': Validate,
             'register': Register}

    # list tasks
    if len(sys.argv) == 1 or "help" in sys.argv[1]:
        print "Syntax: admintool [task] where [task] is one of:"
        for task in tasks:
            print '  %s - %s' % (task, tasks[task](admintool).description)
    # parse arguments
    elif sys.argv[1] in tasks:
        admintool = Admin()
        task = tasks[sys.argv[1]](admintool)
        opt = parseArgs(task, sys.argv)
        resp = task.run()
        if resp is not None:
            print resp
    else:
        print "The task '%s' is not supported by the admin tool" % sys.argv[1]
    sys.exit()
