//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.09 at 02:27:32 PM PST 
//


package edu.caltech.vao.vospace.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The base class for data nodes.
 *       
 * 
 * <p>Java class for DataNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataNodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VOSpace/v2.0}NodeType">
 *       &lt;sequence>
 *         &lt;element name="accepts" type="{http://www.ivoa.net/xml/VOSpace/v2.0}ViewListType" minOccurs="0"/>
 *         &lt;element name="provides" type="{http://www.ivoa.net/xml/VOSpace/v2.0}ViewListType" minOccurs="0"/>
 *         &lt;element name="capabilities" type="{http://www.ivoa.net/xml/VOSpace/v2.0}CapabilityListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="busy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vos:DataNode", propOrder = {
    "accepts",
    "provides",
    "capabilities"
})
@XmlSeeAlso({
    ContainerNodeType.class,
    StructuredDataNodeType.class,
    UnstructuredDataNodeType.class
})
public class DataNodeType
    extends NodeType
{

    protected ViewListType accepts;
    protected ViewListType provides;
    protected CapabilityListType capabilities;
    @XmlAttribute(name = "busy")
    protected Boolean busy;

    /**
     * Gets the value of the accepts property.
     * 
     * @return
     *     possible object is
     *     {@link ViewListType }
     *     
     */
    public ViewListType getAccepts() {
        return accepts;
    }

    /**
     * Sets the value of the accepts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewListType }
     *     
     */
    public void setAccepts(ViewListType value) {
        this.accepts = value;
    }

    /**
     * Gets the value of the provides property.
     * 
     * @return
     *     possible object is
     *     {@link ViewListType }
     *     
     */
    public ViewListType getProvides() {
        return provides;
    }

    /**
     * Sets the value of the provides property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewListType }
     *     
     */
    public void setProvides(ViewListType value) {
        this.provides = value;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityListType }
     *     
     */
    public CapabilityListType getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilityListType }
     *     
     */
    public void setCapabilities(CapabilityListType value) {
        this.capabilities = value;
    }

    /**
     * Gets the value of the busy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBusy() {
        if (busy == null) {
            return false;
        } else {
            return busy;
        }
    }

    /**
     * Sets the value of the busy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBusy(Boolean value) {
        this.busy = value;
    }

}
