//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.09 at 02:27:32 PM PST 
//


package edu.caltech.vao.vospace.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetProtocolsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProtocolsResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accepts" type="{http://www.ivoa.net/xml/VOSpace/v2.0}ProtocolListType"/>
 *         &lt;element name="provides" type="{http://www.ivoa.net/xml/VOSpace/v2.0}ProtocolListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProtocolsResponseType", propOrder = {
    "accepts",
    "provides"
})
public class GetProtocolsResponseType {

    @XmlElement(required = true)
    protected ProtocolListType accepts;
    @XmlElement(required = true)
    protected ProtocolListType provides;

    /**
     * Gets the value of the accepts property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolListType }
     *     
     */
    public ProtocolListType getAccepts() {
        return accepts;
    }

    /**
     * Sets the value of the accepts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolListType }
     *     
     */
    public void setAccepts(ProtocolListType value) {
        this.accepts = value;
    }

    /**
     * Gets the value of the provides property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolListType }
     *     
     */
    public ProtocolListType getProvides() {
        return provides;
    }

    /**
     * Sets the value of the provides property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolListType }
     *     
     */
    public void setProvides(ProtocolListType value) {
        this.provides = value;
    }

}
