FROM alpine:3.7
MAINTAINER <igor.suarez-sola@noirlab.edu

WORKDIR /app
VOLUME /app

RUN apk add --update mysql mysql-client && rm -f /var/cache/apk/*

# These lines moved to the end allow us to rebuild image quickly after only these files were modified.
COPY mysql.startup.sh /startup.sh
COPY mysql.my.cnf /etc/mysql/my.cnf

EXPOSE 3306
CMD ["/startup.sh"]
